### ISSUE TITLE
CSS class name 

### ISSUE THREAD

**Issue by geofjamg** [powsybl/powsybl-single-line-diagram#16]
* **Do you want to request a *feature* or report a *bug*?**
Bad design

* **What is the current behavior?**
To support substation diagram SVG customization, CSS classes are added to graph nodes according to a `SubstationDiagramStyleProvider` implementation. The way it is done is not  standard as CSS class name are generared according node ID. So CSS is dependent of a particular substation. Usually, CSS class are "fixed" and not dependent of the SVG content.  

* **What is the expected behavior?**
CSS should not be generated with the SVG but should be part if the component library and consequently should be the same for all the diagrams. Consequently `SubstationDiagramStyleProvider` interface should be refactored to no generate CSS but just to add classes to nodes.

Proposition for switches to be able by just adding a closed or open class to top level component tag, to change its state. Using this kind of design we won't be able in the DefaultSVGWriter to dive into internal sub component to change switch state. Same could be done for arrows.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg">
    <style><![CDATA[

.BREAKER {
    stroke: rgb(0, 0, 255);
    stroke-width: 2;
    fill: rgb(255, 255, 255);
}

.open .open-switch {
	visibility: visible;
}
.open .closed-switch {
	visibility: hidden;
}
.closed .open-switch {
	visibility: hidden;
}
.closed .closed-switch {
	visibility: visible;
}

]]></style>
    <g>
        <g class="BREAKER closed" id="b" transform="translate(35.0,145.0)">
            <g class="open-switch">
                <rect x="1" width="18" y="1" height="18"/>
                <line y2="15" x1="10" x2="10" y1="5"/>
            </g>
            <g class="closed-switch">
                <rect x="1" width="18" y="1" height="18"/>
                <line y2="10" x1="5" x2="15" y1="10"/>
            </g>
        </g>
    </g>
</svg>
```

* **What is the motivation / use case for changing the behavior?**
To ease the animation od  SVG on client side (change  coloration, switch position, etc).

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by floriand-e2r** [comment]
Since we talked about that issue @geofjamg, I've looked into the code and thought a bit about it. Here are a few thoughts:
- The new CSS file should ideally also contain all the styles provided directly (meaning not through the class attribute), like arrow & node colors, fonts, font size, ...
- The default DiagramStyleProvider has to be refactored, but also the inheriting classes, which have been created since that issue was created:
   - NominalVoltageDiagramStyleProvider, which would provide classes according to the voltage level. The CSS file should then contain the colors of base-voltages.yml file, which is ok 
   - TopologicalStyleProvider, which would provide classes linking to the corresponding busView bus. The CSS file should then contain the n corresponding colors (where n is the number of buses), which is pretty annoying as that's substation-dependent... 
- In the example above, is there a reason for having the invisible open-switch in the SVG? I know that wouldn't be straightforward in the current code but one would expect that the open-switch part is simply not included in the SVG. Unless it is used when the user interacts with the diagram? I mean to change the class 'BREAKER closed' to 'BREAKER open' in the component without regenerating the whole file.
