### ISSUE TITLE
TopologyCalculation is a Final Class

### ISSUE THREAD

**Issue by yasstec** [powsybl/powsybl-single-line-diagram#196]
* **Do you want to request a *feature* or report a *bug*?**

Can you make **com.powsybl.sld.layout.TopologyCalculation** open to extension ?

* **What is the current behavior?**

We need to override the  TopologyCalculation.run method , but the class is final .

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by flo-dup** [comment]
@yasstec I'm not sure you still need this? If not, I'll close the issue.

**Comment by yasstec** [comment]
@flo-dup  Indeed, we created a copy of **com.powsybl.sld.layout.TopologyCalculation** to edit the **run** method. So it might be better if this class is not final.

Thanks for asking.

**Comment by flo-dup** [comment]
Oh, right, didn't know it was only a workaround. I'll open a new PR then.

**Comment by flo-dup** [comment]
I had a closer look to that `TopologyCalculation` class. You wrote that you need to override the run method, but then there's almost nothing left in the class, so extending it is not relevant in my opinion.

Besides, shouldn't you use postprocessing of the result instead of extending that class? Indeed the `TopologicallyConnectedNodesSet` API clearly defines what is a connected nodes set, if you change the run method you're probably obtaining an object which does not respect that API. Or you're filering out some sets, which you'd better do with a post processing of the result.
