### ISSUE TITLE
Possibility to enhance graph object and not only use "Disconnector"

### ISSUE THREAD

**Issue by cedrtheb** [powsybl/powsybl-single-line-diagram#308]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**

* **What is the expected behavior?**
Possibility to add generic object in the graph.
In our modification we need to represent various kinds of objects, and we are forced to tweak them into "Disconnectors". We also need for these kind to carry some parameters as indication for the SVG construction
As examples : 
-Voltage lack indicator (We need it to be on the extremity, just before the arrows)
-Instrument transformers (We also need to keep a left/right direction)

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by yasstec** [comment]
I think we could have a **CustomNode** in SLD model (com.powsybl.sld.model) which extends the **Node** Object , and containing a map of attributes (map to set custom properties like left/right direction ...) so we can access those attributes in the SVGWriter and apply svg transformations (rotation,translation ...) based on those attributes .

**Comment by cedrtheb** [comment]
I agree with you. Just in a semantic way can't we construct Disconector_Node or XXX_Node as child of Node instead of create à new abstract parent ?

**Comment by flo-dup** [comment]
Indeed, a class is missing to properly enable custom components in the graph. So far it is only possible to add custom switches by extending `SwitchNode` class, as the core of the cell detection is expecting only SwitchNodes between the bus bar and the feeder. I think we need to create a new Node type, which would correspond to nodes between the bus bar and the feeder, and then base the cell detection on this node type.

**Comment by flo-dup** [comment]
For the custom properties, I'm not sure this new class will need such a map. I don't see why the class which needs a specific property should not directly have the property in its parameters.
Just a thing about the left/right property taken as example, some kind of switches could also need to have a left or right version (or just a horizontal flip). So it's rather a parameter to add directly in `Node` class.

**Comment by flo-dup** [comment]
About the Voltage lack indicator just after the arrows, thanks to last release you can do it with `DiagramLabelProvider::getFeederInfos`, and add enough space for it by using `LayoutParameters::setMinSpaceForFeederArrows` with the correct value. But that's not really convenient, that's why there's an open issue related to that: #303.

**Comment by flo-dup** [comment]
@BenoitJeanson I think you encountered a very similar problem for a POC, don't you? what do you think about the new node class I'm suggesting above? 

> I think we need to create a new class extending Node, which would correspond to nodes between the bus bar and the feeder, and then base the cell detection on this node type.

Would it have been a solution for you also?

**Comment by flo-dup** [comment]
Good thing to introduce `EquipmentNode` vs `ConnectivityNode`, it's pretty clear that way. So in fact the BlockDecomposer algorithm will simply look for the pattern n*`EquipmentNode` instead of n*`SwitchNode`. 

And good thing to remove/rename `FictitiousNode`; "Fictitious" is indeed quite misleading, we should keep it as an attribute only.

The only problem I see is the `Middle3WTNode`, which is expected to be an `EquipmentNode` but which is used as a `ConnectivityNode` in the cell detection. For the sake of clarity I think we should therefore add an `InternalNode` before the `Middle3WTNode`, or maybe 2 after, between each `Feeder3WTLegNode` and the `Middle3WTNode`. Then a `Middle3WTNode` could be an equipment node. What do you think?

Very nice proposal, I think such a refactor is a lot better than just patching the existing design. Thanks @BenoitJeanson !

**Comment by flo-dup** [comment]
@cedrtheb I think the design proposed by Benoit would also fit your needs, do you agree on that?
