### ISSUE TITLE
Update Mockito (testing) for OpenJDK 18

### ISSUE THREAD

**Issue by bulvara** [powsybl/powsybl-single-line-diagram#398]
Example error:
```
[ERROR] testRemoveExtensions(com.powsybl.sld.cgmes.dl.conversion.CgmesDLImporterTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.mockito.internal.creation.cglib.ClassImposterizer$3
	at com.powsybl.sld.cgmes.dl.conversion.CgmesDLImporterTest.setUp(CgmesDLImporterTest.java:35)
```
https://github.com/mockito/mockito/issues/638

Please update Mockito for OpenJDK 18 compatibility

**Comment by flo-dup** [comment]
You shouldn't encounter this if you're up-to-date, do you have a powsybl-single-line-diagram version < 2.2.0?

Indeed, Mockito version is >= 3.3.3 since powsybl-core 3.4.0 (17 Jun 2020) and 4.4.0 since powsybl-core 4.9.0 (13 Jun 2022), and powsybl-single-line-diagram inherits that version since it imports powsybl-core pom since 2.2.0 release (26 May 2021). And it's even 4.4.0 since powsybl-core 4.9.0, which was release just after you wrote this.

**Comment by flo-dup** [comment]
Closing as it is solved by updating to a more recent version. Feel free to reopen if I'm mistaken.
